/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-932"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20151223"
#define PACKAGE_DATE_STRING "13 Apr 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "932"
#define REV_BINARY_SHA "04a91ab9174ead54f1ed59d79eef30169a85a8e0b0d5c8c78e5069ff003a678e"
#define GIT_BRANCH "titles/gta-ViceCity"
#define GIT_REV_DATE "20151223-7"
#define GIT_HASH_BINARY "aaf97d66e500a877e4d0cfd61917b9d5a1a21c98"

