/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-632"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20151123"
#define PACKAGE_DATE_STRING "23 Nov 15"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "632"
#define REV_BINARY_SHA "cd8bfe549f40a97cf4548b2cd8874e9a6283a9d7484cda79d3764cc2d85a9630"
#define GIT_BRANCH "master"
#define GIT_REV_DATE "20151123-5"
#define GIT_HASH_BINARY "39bce0e5061268162c2873895252cdcd5f2c9876"

